<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Six - JS.next Transpiler: version 1.0</string>
	<key>fileTypes</key>
	<array>
		<string>six</string>
		<string>six.js</string>
		<string>Sakefile</string>
		<string>Sixfile</string>
	</array>
	<key>name</key>
	<string>Six</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#arrow-function</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([g|s]et\s+)?([a-zA-Z_$]+)(?&lt;!function)\s*(?=\([a-zA-Z_$,\s]*\)\s*\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.six</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.six</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\))\s*\{</string>
			<key>name</key>
			<string>meta.function.six</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.function.parameter.list.six</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z_$]+</string>
							<key>name</key>
							<string>variable.parameter.function.six</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.six</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Match stuff like: module name {...}</string>
			<key>match</key>
			<string>\b(module)\s*(\s*[a-zA-Z0-9_?.$][\w?.$]*)\s*</string>
			<key>name</key>
			<string>meta.function.six</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(`)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.six</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(`)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.six</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.template.six</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\$){</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.six</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.template.replacement.six</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.quoted.double.six</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arrow-function</key>
		<dict>
			<key>begin</key>
			<string>(?:([a-zA-Z_$]*)\s*([=:]{1})\s*)?(?=(?:\([a-zA-Z_$,\s]*\)\s*(?==&gt;))?(?:(?&lt;!\))[a-zA-Z_$]*)?\s*=&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.six</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.six</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(=&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.six</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.six</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.function.parameter.list.six</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z_$]+</string>
							<key>name</key>
							<string>variable.parameter.function.six</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_$]+(?!\))\s*(?==&gt;)</string>
					<key>name</key>
					<string>variable.parameter.function.six</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.six</string>
	<key>uuid</key>
	<string>623fff25-01b9-481b-a89c-af5ba523d30c</string>
</dict>
</plist>
